Fix / Workaround for: Error in regex: target of repeat operator is invalid in regex
Fixes: #242

SublimeText 4 (as of build 4121) evaluates this valid regex: `\n?` to this invalid one: `$?`
hence causing the following error:

```
error: Error loading syntax file "Packages/<Path_To>.tmLanguage": Error in regex: target of repeat operator is invalid in regex
```

This commit is a workaround to fix this problem.